[versions]
sdkCompile = "36"
sdkMin = "26"
sdkTarget = "36"

aboutLibraries = "12.2.3"
accompanist = "0.37.3"
acra = "5.12.0"
androidGradlePlugin = "8.10.1"
androidTools = "31.10.1"
androidxActivity = "1.10.1"
androidxComposeBom = "2025.06.01"
androidxCore = "1.16.0"
androidxCoreSplashscreen = "1.0.1"
androidxDataStore = "1.1.7"
androidxEspresso = "3.6.1"
androidxGlance = "1.1.1"
androidxLifecycle = "2.9.1"
androidxLifecycleViewmodelCompose = "2.9.1"
androidxNavigation = "2.9.0"
androidxWindowManager = "1.4.0"
androidxWork = "2.10.2"
auto-service = "1.1.1"
auto-service-ksp = "1.2.0"
coil = "3.2.0"
detektPlugin = "1.23.8"
detektCompose = "0.4.22"
hilt = "2.56.2"
hiltExt = "1.2.0"
junit4 = "4.13.2"
junitExt = "1.2.1"
kotest = "6.0.0.M3"
kotlin = "2.1.21"
kotlinxCoroutines = "1.10.2"
kotlinxCollectionImmutable = "0.4.0"
kotlinxSerializationJson = "1.8.1"
ksp = "2.1.21-2.0.2"
materialKolor = "2.1.1"
okhttpBom = "4.12.0"
okhttpCoroutines = "1.0"
palette = "1.0.0"
protobuf = "4.30.2"
protobufPlugin = "0.9.5"
room = "2.7.2"
turbine = "1.2.0"
uuidCreator = "6.0.0"
zoomable = "2.7.0"

[libraries]
aboutLibraries-core = { group = "com.mikepenz", name = "aboutlibraries-core", version.ref = "aboutLibraries" }
aboutLibraries-material3 = { group = "com.mikepenz", name = "aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
acra-core = { group = "ch.acra", name = "acra-core", version.ref = "acra" }
acra-mail = { group = "ch.acra", name = "acra-mail", version.ref = "acra" }
acra-dialog = { group = "ch.acra", name = "acra-dialog", version.ref = "acra" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui-testJunit = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-toolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-datastoreCore = { group = "androidx.datastore", name = "datastore", version.ref = "androidxDataStore" }
androidx-glance = { group = "androidx.glance", name = "glance", version.ref = "androidxGlance" }
androidx-glanceAppWidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "androidxGlance" }
androidx-glanceMaterial3 = { group = "androidx.glance", name = "glance-material3", version.ref = "androidxGlance" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltExt" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycleViewmodelCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-palette = { group = "androidx.palette", name = "palette-ktx", version.ref = "palette"  }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-windowManager = { group = "androidx.window", name = "window", version.ref = "androidxWindowManager" }
androidx-workKtx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWork" }
auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "auto-service"}
auto-service-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version.ref = "auto-service-ksp"}
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detektPlugin" }
detekt-compose = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "detektCompose" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
hilt-ext-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltExt" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
kotest = { group = "io.kotest", name = "kotest-assertions-core-jvm", version.ref = "kotest" }
kotlinx-coroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutinesTest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-collectionImmutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxCollectionImmutable" }
kotlinx-serializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
materialKolor = { group = "com.materialkolor", name = "material-kolor", version.ref = "materialKolor" }
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttpBom" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp" }
okhttp-loggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor" }
okhttp-mockWebServer = { group = "com.squareup.okhttp3", name = "mockwebserver" }
okhttp-coroutines = { group = "ru.gildor.coroutines", name = "kotlin-coroutines-okhttp", version.ref = "okhttpCoroutines" }
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
uuid-creator = { module = "com.github.f4b6a3:uuid-creator", version.ref = "uuidCreator" }
zoomable = { module = "net.engawapg.lib:zoomable-android", version.ref = "zoomable" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detektPlugin" }

[plugins]
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektPlugin" }

# Plugins defined by this project
musicrecognizer-android-application = { id = "musicrecognizer.android.application", version = "unspecified" }
musicrecognizer-android-application-compose = { id = "musicrecognizer.android.application.compose", version = "unspecified" }
musicrecognizer-android-library = { id = "musicrecognizer.android.library", version = "unspecified" }
musicrecognizer-android-library-compose = { id = "musicrecognizer.android.library.compose", version = "unspecified" }
musicrecognizer-android-feature = { id = "musicrecognizer.android.feature", version = "unspecified" }
musicrecognizer-hilt = { id = "musicrecognizer.hilt", version = "unspecified" }
musicrecognizer-jvm-library = { id = "musicrecognizer.jvm.library", version = "unspecified" }
